Imports

In [1]:
import torch
import torch.nn as nn
import pandas as pd
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader

target = pd.read_csv('sample_submission.csv')
test = pd.read_csv('test.csv')
train = pd.read_csv('train.csv',index_col='PassengerId')

MODEL

In [2]:
class LogisticRegression(nn.Module):
    def __init__(self, n_input=12, n_hidden=24, n_output=1) -> None:
        super().__init__()

        self.linear_1 = nn.Linear(n_input, n_hidden)
        self.linear_2 = nn.Linear(n_input, n_output)

        self.sigmoid = nn.Sigmoid()
        self.softmax = nn.Softmax()

    def forward(self,x):
        x = self.linear_1(x)
        x = self.sigmoid(x)
        x = self.linear_2(x)
        x = self.softmax(x)
        return x


Dataset

In [56]:
class PassangerDataset(Dataset):
    def __init__(self, dataframe):
        self.dataframe = dataframe
        self.y = torch.tensor(dataframe['Transported'].values)
        kurde = [dataframe.drop('Transported', axis=1).values.astype('float32')]
        print(kurde)
        self.x = torch.tensor(kurde,dtype=torch.float32).view(-1,1)

    def __getitem__(self, index):
        print(self.x)
        return self.x[index],self.y[index]

    def __len__(self):
        return len(self.dataframe)

Data cleaning

In [57]:


Y_train = train['Transported']
X_train = train.drop(columns=['Name'])
X_train[['Cabin_1','Cabin_2','Cabin_3']] = X_train['Cabin'].str.split('/').apply(pd.Series)
X_train = X_train.drop(columns='Cabin')
X_train = pd.get_dummies(X_train,columns=['HomePlanet','Destination','Cabin_1','Cabin_3'])


X_train.head()

dataset = PassangerDataset(X_train)
dataloader = DataLoader(dataset)

for sample in dataloader:
    print(sample)

# Y_train.head()
# X_train = torch.tensor()

[array([[ 0., 39.,  0., ...,  0.,  1.,  0.],
       [ 0., 24.,  0., ...,  0.,  0.,  1.],
       [ 0., 58.,  1., ...,  0.,  0.,  1.],
       ...,
       [ 0., 26.,  0., ...,  0.,  0.,  1.],
       [ 0., 32.,  0., ...,  0.,  0.,  1.],
       [ 0., 44.,  0., ...,  0.,  0.,  1.]], dtype=float32)]
tensor([[ 0.],
        [39.],
        [ 0.],
        ...,
        [ 0.],
        [ 0.],
        [ 1.]])
[tensor([[0.]]), tensor([False])]
tensor([[ 0.],
        [39.],
        [ 0.],
        ...,
        [ 0.],
        [ 0.],
        [ 1.]])
[tensor([[39.]]), tensor([True])]
tensor([[ 0.],
        [39.],
        [ 0.],
        ...,
        [ 0.],
        [ 0.],
        [ 1.]])
[tensor([[0.]]), tensor([False])]
tensor([[ 0.],
        [39.],
        [ 0.],
        ...,
        [ 0.],
        [ 0.],
        [ 1.]])
[tensor([[0.]]), tensor([False])]
tensor([[ 0.],
        [39.],
        [ 0.],
        ...,
        [ 0.],
        [ 0.],
        [ 1.]])
[tensor([[0.]]), tensor([True])]
tensor([[ 0.],
  

In [27]:
train.drop('Transported',axis=1)

HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
PassengerId                                                              
0001_01         Europa     False     B/0/P    TRAPPIST-1e  39.0  False   
0002_01          Earth     False     F/0/S    TRAPPIST-1e  24.0  False   
0003_01         Europa     False     A/0/S    TRAPPIST-1e  58.0   True   
0003_02         Europa     False     A/0/S    TRAPPIST-1e  33.0  False   
0004_01          Earth     False     F/1/S    TRAPPIST-1e  16.0  False   
...                ...       ...       ...            ...   ...    ...   
9276_01         Europa     False    A/98/P    55 Cancri e  41.0   True   
9278_01          Earth      True  G/1499/S  PSO J318.5-22  18.0  False   
9279_01          Earth     False  G/1500/S    TRAPPIST-1e  26.0  False   
9280_01         Europa     False   E/608/S    55 Cancri e  32.0  False   
9280_02         Europa     False   E/608/S    TRAPPIST-1e  44.0  False   

             RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  \
PassengerId                                                         
0001_01              0.0        0.0           0.0     0.0     0.0   
0002_01            109.0        9.0          25.0   549.0    44.0   
0003_01             43.0     3576.0           0.0  6715.0    49.0   
0003_02              0.0     1283.0         371.0  3329.0   193.0   
0004_01            303.0       70.0         151.0   565.0     2.0   
...                  ...        ...           ...     ...     ...   
9276_01              0.0     6819.0           0.0  1643.0    74.0   
9278_01              0.0        0.0           0.0     0.0     0.0   
9279_01              0.0        0.0        1872.0     1.0     0.0   
9280_01              0.0     1049.0           0.0   353.0  3235.0   
9280_02            126.0     4688.0           0.0     0.0    12.0   

                          Name  
PassengerId                     
0001_01        Maham Ofracculy  
0002_01           Juanna Vines  
0003_01          Altark Susent  
0003_02           Solam Susent  
0004_01      Willy Santantines  
...                        ...  
9276_01      Gravior Noxnuther  
9278_01        Kurta Mondalley  
9279_01           Fayey Connon  
9280_01       Celeon Hontichre  
9280_02       Propsh Hontichre  

[8693 rows x 12 columns]